[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-run --chip RP2040"

# runner = "elf2uf2-rs -d"

# with debug.gdb setup script
# runner = "gdb-multiarch -q -x debug.gdb target/thumbv6m-none-eabi/debug/netbox-hardware"

# runner = "cargo embed"

[build]
target = "thumbv6m-none-eabi" # Cortex-M0 and Cortex-M0+

[alias]
rb = "run --target thumbv6m-none-eabi --bin"
rrb = "run --target thumbv6m-none-eabi --release --bin"
# xtask = "run --manifest-path xtask/Cargo.toml --"

[env]
DEFMT_LOG = "debug"
